//
//  SynthWaveKit.swift
//  DigitalD1
//
//  Created by Matthew Fecher on 10/10/18.
//  Copyright © 2018 AudioKit. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

import UIKit

public class SynthWaveKit: NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawSynthWavePicker(controlValue: CGFloat = 1) {
        //// Color Declarations
        let selected = UIColor(red: 0.537, green: 0.898, blue: 0.976, alpha: 1.000)
        let unselected = UIColor(red: 0.333, green: 0.333, blue: 0.333, alpha: 1.000)

        //// Variable Declarations
        let sineColor = controlValue == 1 ? selected : unselected
        let squareColor = controlValue == 2 ? selected : unselected
        let triangleColor = controlValue == 3 ? selected : unselected
        let sawColor = controlValue == 4 ? selected : unselected

        //// Square Drawing
        let squarePath = UIBezierPath()
        squarePath.move(to: CGPoint(x: 64, y: 22))
        squarePath.addLine(to: CGPoint(x: 64, y: 14))
        squarePath.addLine(to: CGPoint(x: 73, y: 14))
        squarePath.addLine(to: CGPoint(x: 73, y: 31))
        squarePath.addLine(to: CGPoint(x: 82, y: 31))
        squareColor.setStroke()
        squarePath.lineWidth = 1.5
        squarePath.lineCapStyle = .round
        squarePath.stroke()

        //// SineWave Drawing
        let sineWavePath = UIBezierPath()
        sineWavePath.move(to: CGPoint(x: 12, y: 22))
        sineWavePath.addCurve(to: CGPoint(x: 17, y: 14), controlPoint1: CGPoint(x: 12, y: 22), controlPoint2: CGPoint(x: 10.85, y: 14))
        sineWavePath.addCurve(to: CGPoint(x: 24.34, y: 31), controlPoint1: CGPoint(x: 23.15, y: 14), controlPoint2: CGPoint(x: 16.13, y: 31))
        sineWavePath.move(to: CGPoint(x: 37, y: 22))
        sineWavePath.addCurve(to: CGPoint(x: 32, y: 14), controlPoint1: CGPoint(x: 37, y: 22), controlPoint2: CGPoint(x: 38.15, y: 14))
        sineWavePath.addCurve(to: CGPoint(x: 24.34, y: 31), controlPoint1: CGPoint(x: 25.85, y: 14), controlPoint2: CGPoint(x: 32.54, y: 31))
        sineColor.setStroke()
        sineWavePath.lineWidth = 1.5
        sineWavePath.lineCapStyle = .round
        sineWavePath.stroke()

        //// Saw
        //// UpSaw Drawing
        let upSawPath = UIBezierPath()
        upSawPath.move(to: CGPoint(x: 71, y: 74))
        upSawPath.addLine(to: CGPoint(x: 71, y: 58))
        upSawPath.addLine(to: CGPoint(x: 64, y: 67))
        sawColor.setStroke()
        upSawPath.lineWidth = 1.5
        upSawPath.lineCapStyle = .round
        upSawPath.stroke()

        //// UpSaw 2 Drawing
        let upSaw2Path = UIBezierPath()
        upSaw2Path.move(to: CGPoint(x: 84, y: 74))
        upSaw2Path.addLine(to: CGPoint(x: 84, y: 58))
        upSaw2Path.addLine(to: CGPoint(x: 71, y: 74))
        sawColor.setStroke()
        upSaw2Path.lineWidth = 1.5
        upSaw2Path.lineCapStyle = .round
        upSaw2Path.stroke()

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 84, y: 74))
        bezierPath.addLine(to: CGPoint(x: 90, y: 64))
        sawColor.setStroke()
        bezierPath.lineWidth = 1.5
        bezierPath.lineCapStyle = .round
        bezierPath.stroke()

        //// Triangle
        //// UpSaw 4 Drawing
        let upSaw4Path = UIBezierPath()
        upSaw4Path.move(to: CGPoint(x: 24, y: 58))
        upSaw4Path.addLine(to: CGPoint(x: 14, y: 74))
        triangleColor.setStroke()
        upSaw4Path.lineWidth = 1.5
        upSaw4Path.lineCapStyle = .round
        upSaw4Path.stroke()

        //// UpSaw 3 Drawing
        let upSaw3Path = UIBezierPath()
        upSaw3Path.move(to: CGPoint(x: 24, y: 58))
        upSaw3Path.addLine(to: CGPoint(x: 35, y: 74))
        triangleColor.setStroke()
        upSaw3Path.lineWidth = 1.5
        upSaw3Path.lineCapStyle = .round
        upSaw3Path.stroke()

        //// Square 2 Drawing
        let square2Path = UIBezierPath()
        square2Path.move(to: CGPoint(x: 91, y: 22))
        square2Path.addLine(to: CGPoint(x: 91, y: 14))
        square2Path.addLine(to: CGPoint(x: 82, y: 14))
        square2Path.addLine(to: CGPoint(x: 82, y: 31))
        square2Path.addLine(to: CGPoint(x: 73, y: 31))
        squareColor.setStroke()
        square2Path.lineWidth = 1.5
        square2Path.lineCapStyle = .round
        square2Path.stroke()
    }

}
